//------------------------------------------------------------------------------
// <auto-generated>
//     Este código se generó a partir de una plantilla.
//
//     Los cambios manuales en este archivo pueden causar un comportamiento inesperado de la aplicación.
//     Los cambios manuales en este archivo se sobrescribirán si se regenera el código.
// </auto-generated>
//------------------------------------------------------------------------------

namespace examen3Ventas2019
{
    using System;
    using System.Collections.Generic;
    
    public partial class CLIENTE
    {
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2214:DoNotCallOverridableMethodsInConstructors")]
        public CLIENTE()
        {
            this.BOLETA = new HashSet<BOLETA>();
        }
    
        public string COD_CLI { get; set; }
        public string NOMBRES { get; set; }
        public string APE_PATER_CLI { get; set; }
        public string APE_MATER_CLI { get; set; }
        public string DIRECCION_CLI { get; set; }
        public string TELEFONO_CLI { get; set; }
        public string COD_DIST { get; set; }
        public string CORREO_E { get; set; }
    
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<BOLETA> BOLETA { get; set; }
        public virtual DISTRITO DISTRITO { get; set; }
    }
}
