//------------------------------------------------------------------------------
// <auto-generated>
//     Este código se generó a partir de una plantilla.
//
//     Los cambios manuales en este archivo pueden causar un comportamiento inesperado de la aplicación.
//     Los cambios manuales en este archivo se sobrescribirán si se regenera el código.
// </auto-generated>
//------------------------------------------------------------------------------

namespace examen3Ventas2019
{
    using System;
    using System.Collections.Generic;
    
    public partial class DETALLEBOLETA
    {
        public string COD_BOL { get; set; }
        public string COD_PRO { get; set; }
        public int CANTIDAD { get; set; }
        public Nullable<decimal> PRECIOVENTA { get; set; }
    
        public virtual BOLETA BOLETA { get; set; }
        public virtual PRODUCTO PRODUCTO { get; set; }
    }
}
