//------------------------------------------------------------------------------
// <auto-generated>
//     Este código se generó a partir de una plantilla.
//
//     Los cambios manuales en este archivo pueden causar un comportamiento inesperado de la aplicación.
//     Los cambios manuales en este archivo se sobrescribirán si se regenera el código.
// </auto-generated>
//------------------------------------------------------------------------------

namespace examen3Ventas2019
{
    using System;
    using System.Collections.Generic;
    
    public partial class PRODUCTO
    {
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2214:DoNotCallOverridableMethodsInConstructors")]
        public PRODUCTO()
        {
            this.DETALLEBOLETA = new HashSet<DETALLEBOLETA>();
        }
    
        public string COD_PRO { get; set; }
        public string DESCRIP_PRO { get; set; }
        public decimal PRECIO_PRO { get; set; }
        public int STOCK_ACT_PRO { get; set; }
        public int STOCK_MIN_PRO { get; set; }
    
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<DETALLEBOLETA> DETALLEBOLETA { get; set; }
    }
}
